"""empty message

Revision ID: 391500623670
Revises: 1aad956db6d3
Create Date: 2025-02-26 17:30:34.504946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391500623670'
down_revision = '1aad956db6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=260), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
